# **신경망의 추론 처리**

MNIST 데이터 셋을 가지고 추론을 수행하는 신경망 구현

In [3]:
import sys, os
sys.path.append(os.pardir)
from dataset.mnist import load_mnist
import pickle
import numpy as np

In [4]:
def sigmoid(x):
    return 1 / (1+np.exp(-x))

In [5]:
def softmax(a):
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    return y

In [6]:
def get_data():
    (x_train, t_train), (x_test, t_test) = \
        load_mnist(normalize=True, flatten=True, one_hot_label=False)
    return x_test, t_test

In [7]:
def init_network():
    with open("dataset/sample_weight.pkl", 'rb') as f:
        network = pickle.load(f)#sample_weight load
        
    return network

In [8]:
def predict(network, x): #예측부분, 뉴럴네트워크와 입력이 인자로 들어감
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']
    
    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2, W3) + b3
    y = softmax(a3)
    
    return y #결과

In [9]:
x, t = get_data() #이미지 불러오기

In [10]:
x.shape, t.shape

((10000, 784), (10000,))

In [39]:
len(x)

10000

총 1000개의 데이터

정확도 평가

In [12]:
network = init_network()

In [14]:
network['W1']

array([[-0.00741249, -0.00790439, -0.01307499, ...,  0.01978721,
        -0.04331266, -0.01350104],
       [-0.01029745, -0.01616653, -0.01228376, ...,  0.01920228,
         0.02809811,  0.01450908],
       [-0.01309184, -0.00244747, -0.0177224 , ...,  0.00944778,
         0.01387301,  0.03393568],
       ...,
       [ 0.02242565, -0.0296145 , -0.06326169, ..., -0.01012643,
         0.01120969,  0.01027199],
       [-0.00761533,  0.02028973, -0.01498873, ...,  0.02735376,
        -0.01229855,  0.02407041],
       [ 0.00027915, -0.06848375,  0.00911191, ..., -0.03183098,
         0.00743086, -0.04021148]], dtype=float32)

In [16]:
network['b1']

array([-0.06750315,  0.0695926 , -0.02730473,  0.02256093, -0.22001474,
       -0.22038847,  0.04862635,  0.13499236,  0.23342554, -0.0487357 ,
        0.10170191, -0.03076038,  0.15482435,  0.05212503,  0.06017235,
       -0.03364862, -0.11218343, -0.26460695, -0.03323386,  0.13610415,
        0.06354368,  0.04679805, -0.01621654, -0.05775835, -0.03108677,
        0.10366164, -0.0845938 ,  0.11665157,  0.21852103,  0.04437255,
        0.03378392, -0.01720384, -0.07383765,  0.16152057, -0.10621249,
       -0.01646949,  0.00913961,  0.10238428,  0.00916639, -0.0564299 ,
       -0.10607515,  0.09892716, -0.07136887, -0.06349134,  0.12461706,
        0.02242282, -0.00047972,  0.04527043, -0.15179175,  0.10716812],
      dtype=float32)

In [28]:
network['W3'].shape, network['b3'].shape

((100, 10), (10,))

In [29]:
y=predict(network, x[0])

In [30]:
y.shape

(10,)

In [31]:
y

array([8.4412466e-05, 2.6350647e-06, 7.1549427e-04, 1.2586263e-03,
       1.1727955e-06, 4.4990826e-05, 1.6269301e-08, 9.9706495e-01,
       9.3744720e-06, 8.1831153e-04], dtype=float32)

In [32]:
np.max(y)

0.99706495

In [34]:
np.argmax(y) #가장큰 인덱스의 클래스값

7

In [38]:
accuracy_cnt = 0

for i in range(len(x)):
    y = predict(network, x[i]) #네트워크와 이미지를 넣어서 결과예측
    p = np.argmax(y) #가장큰 클래스 값을 알려줌
    if p == t[i]: #결과가 정답과 같은지 확인
        accuracy_cnt += 1
print("Accuracy:" + str(float(accuracy_cnt) / len(x)))

Accuracy:0.9352


In [32]:
title = 'Ans #{}, Pred.#{}, {:.4f}'.format(t[0], np.argmax(y), np.max(y))
print(title)

Ans #7, Pred.#7, 0.9971


In [35]:
len(x)

10000

## 랜덤으로 몇개만 뽑아서 테스트 해보기

In [40]:
idx_test = np.random.choice(len(x), 100)

In [41]:
idx_test

array([1955, 2483, 2483, 2075, 9440, 1455, 7876, 9987, 6948, 4587,  488,
       2240,  613, 3399, 5406, 8922, 9543, 6534, 5196, 1026, 8282, 7214,
       7154, 1816,    3, 6980,  279, 5713,  558, 7190, 8412, 2254, 3474,
       1859, 3359, 9860, 3294,  475, 5689, 1818, 2980, 6178, 9711, 7324,
       2669, 3340, 7941, 5100, 3970, 1959, 8633, 3628, 5957, 2946, 6283,
       7761, 6813, 4160, 9773, 8300, 1963, 5309, 5251, 1835, 1515, 7524,
       8981, 8258, 6812, 3831, 3378, 6917, 3259, 4189, 3195, 1826, 4241,
       2848,  808,  964,  773, 8548, 1051, 9930, 4499,  844, 4622, 4721,
       5853, 3400, 1452, 3797, 3149, 3221, 6576, 7426, 8464, 4481, 2410,
        660])

In [42]:
x_select = x[idx_test]
y_select = t[idx_test]

In [43]:
x_select.shape

(100, 784)

In [44]:
accuracy_cnt = 0
for i in range(len(x_select)):
    y = predict(network, x_select[i])
    
    p = np.argmax(y) # 확률이 가장 높은 원소의 인덱스를 얻는다.
    
    if p == y_select[i]:
        accuracy_cnt += 1

In [45]:
accuracy_cnt / len(x_select)

0.97

100개 중 97개 맞힘