# **Math Primer for AI**

In [2]:
import numpy as np

## **Matrix multiplication**

두 array의 행렬곱

In [3]:
a = np.array([[1, -3, 2], [4, 0, -5]])
print(a)

[[ 1 -3  2]
 [ 4  0 -5]]


In [4]:
a.shape

(2, 3)

In [5]:
b = np.array([[3],[1],[2]])
print(b)

[[3]
 [1]
 [2]]


In [6]:
b.shape

(3, 1)

In [7]:
c = np.matmul(a,b) #matrix multiplicatioin
print(c)

[[4]
 [2]]


In [9]:
c.shape # a의 2(행), b의 1(열)

(2, 1)

matrix multiplication 설명 참고 영상 : 
https://www.youtube.com/watch?v=2spTnAiQg4M

In [10]:
d = np.dot(a,b)
print(d)

[[4]
 [2]]


In [11]:
d.shape

(2, 1)

두 행렬이 2차원이라면, dot과 matmul은 같은 기능을 한다.